# --- !Ups

CREATE TABLE LOGIN_INFO (
  ID                      BIGINT NOT NULL AUTO_INCREMENT,
  PROVIDER_ID             VARCHAR(254) NOT NULL,
  PROVIDER_KEY            VARCHAR(254) NOT NULL,
  CREATED_TIME            TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  MODIFIED_TIME           TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    ON UPDATE               CURRENT_TIMESTAMP,
  CONSTRAINT              LINFO_PROVIDER_ID_PROVIDER_KEY_UC
    UNIQUE                  (PROVIDER_ID, PROVIDER_KEY),
  PRIMARY KEY             (ID)
);

# --- !Downs

SET UNIQUE_CHECKS = 0;
SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS LOGIN_INFO;
SET FOREIGN_KEY_CHECKS = 1;
SET UNIQUE_CHECKS = 1;
