# --- !Ups

CREATE TABLE USER_X_LOGIN_INFO (
  ID                      BIGINT NOT NULL AUTO_INCREMENT,
  LOGIN_INFO_ID           BIGINT NOT NULL,
  USER_ID                 BIGINT NOT NULL,
  CREATED_TIME            TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  MODIFIED_TIME           TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    ON UPDATE               CURRENT_TIMESTAMP,
  CONSTRAINT              UXLINFO_LOGIN_INFO_FK
    FOREIGN KEY             (LOGIN_INFO_ID)
    REFERENCES              LOGIN_INFO (ID),
  CONSTRAINT              UXLINFO_USER_FK
    FOREIGN KEY             (USER_ID)
    REFERENCES              USER (ID),
  CONSTRAINT              UXLINFO_LOGIN_INFO_ID_UC
    UNIQUE                  (LOGIN_INFO_ID),
  PRIMARY KEY             (ID)
);

# --- !Downs

SET UNIQUE_CHECKS = 0;
SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS USER_X_LOGIN_INFO;
SET FOREIGN_KEY_CHECKS = 1;
SET UNIQUE_CHECKS = 1;
