# --- !Ups

CREATE TABLE OAUTH1_INFO (
  ID              BIGINT NOT NULL AUTO_INCREMENT,
  LOGIN_INFO_ID   BIGINT NOT NULL,
  ACCESS_SECRET   VARCHAR(512) NOT NULL,
  ACCESS_TOKEN    VARCHAR(512) NOT NULL,
  CREATED_TIME    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  MODIFIED_TIME   TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    ON UPDATE       CURRENT_TIMESTAMP,
  PRIMARY KEY     (ID)
);

# --- !Downs

SET UNIQUE_CHECKS = 0;
SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS OAUTH1_INFO;
SET FOREIGN_KEY_CHECKS = 1;
SET UNIQUE_CHECKS = 1;
