# --- !Ups

CREATE TABLE PASSWORD_INFO (
  ID                      BIGINT NOT NULL AUTO_INCREMENT,
  LOGIN_INFO_ID           BIGINT NOT NULL,
  HASHER                  VARCHAR(254) NOT NULL,
  PASSWORD                VARCHAR(254) NOT NULL,
  SALT                    VARCHAR(254),
  CREATED_TIME            TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  MODIFIED_TIME           TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    ON UPDATE               CURRENT_TIMESTAMP,
  CONSTRAINT              PINFO_LOGIN_INFO_FK
    FOREIGN KEY             (LOGIN_INFO_ID)
    REFERENCES              LOGIN_INFO (ID),
  CONSTRAINT              PINFO_LOGIN_INFO_ID_UC
    UNIQUE                  (LOGIN_INFO_ID),
  PRIMARY KEY             (ID)
);

# --- !Downs

SET UNIQUE_CHECKS = 0;
SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS PASSWORD_INFO;
SET FOREIGN_KEY_CHECKS = 1;
SET UNIQUE_CHECKS = 1;
