# --- !Ups

CREATE TABLE USER_TOKEN (
  ID                      BIGINT NOT NULL AUTO_INCREMENT,
  USER_ID                 BIGINT NOT NULL,
  TOKEN_ID                VARCHAR(64) NOT NULL,
  EXPIRES_ON              TIMESTAMP(3) NOT NULL,
  CREATED_TIME            TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  MODIFIED_TIME           TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    ON UPDATE               CURRENT_TIMESTAMP,
  CONSTRAINT              UTOKEN_USER_FK
    FOREIGN KEY             (USER_ID)
    REFERENCES              USER (ID),
  CONSTRAINT              UTOKEN_USER_ID_UC
    UNIQUE                  (USER_ID),
  PRIMARY KEY             (ID)
);

# --- !Downs

SET UNIQUE_CHECKS = 0;
SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS USER_TOKEN;
SET FOREIGN_KEY_CHECKS = 1;
SET UNIQUE_CHECKS = 1;
